### PR TITLE
Camera - Android Updates

### PR DESCRIPTION
**Pull request by AndrewEQ**
- updated with new file permission requirements for newer androids.
- catered for out of memory error
  - post photo capture - rotation fix: if out of memory, won't crash but will downsize image to fit memory before adjusting rotation
- fixed android app name

https://medium.com/@andrewq/hello-world-eaa996c594b7

This PR contains:
- [ ] Changelog
- [ ] Documentation
- [ ] Tests

### CODE REVIEW

**Comment by AndrewEQ** [comment]
https://github.com/fuse-open/fuselibs/issues/1235
https://github.com/fuse-open/fuselibs/issues/542
https://github.com/fuse-open/fuselibs/issues/932

**Comment by kusma** [comment]
```
ERROR: /com: Access to the path "/com" is denied.
ERROR: /com/fuse: Access to the path "/com" is denied.
ERROR: /com/fuse/fileprovider: Access to the path "/com" is denied.
```

**Comment by AndrewEQ** [comment]
So this line isn't working for you? https://github.com/fuse-open/fuselibs/pull/1254/files#diff-d4078f67c4477fe19bd1e2986f56762fR3

Should I use a ```<CopyFile />``` tag rather?

**Comment by AndrewEQ** [comment]
Ok, figured it out, its sorted.

**Comment by ckarmy** [comment]
:)

**Comment by ckarmy** [comment]
Work perfect to me!

**Pull request merged**
