### PR TITLE
Fuse.Maps Fix

### PR DESCRIPTION
**Pull request by AndrewEQ**
Need the google repo to download the maps play services

** Briefly describe changes and the motivation behind them here **

This PR contains:
- [ ] Changelog
- [ ] Documentation
- [ ] Tests

### CODE REVIEW

**Comment by kusma** [comment]
This looks like the same as #1221... Why do you keep closing PRs and reopening identical ones? You know that you can force-push a branch to update the PR, right?

**Comment by AndrewEQ** [comment]
Hey @kusma, yeah I did but it auto-closed the PR.

**Comment by AndrewEQ** [comment]
@kusma can you share the GitHub workflow & tools you would like us to follow?
Perhaps include it in a standards doc for the community?

I was using a combination of terminal and GitHub Desktop, perhaps that was the cause, I'm not sure.

**Comment by kusma** [comment]
I use git from the command line, but I don't really care how people use it. I care only about the outcome.

There's a reopen-button on the other PR, but it's grayed out due to this PR. I'll try to close this and see if I can reopen that one instead.

**Pull request closed without merging**
